FROM elixir:1.5.1

# Install hex
RUN /usr/local/bin/mix local.hex --force && \
    /usr/local/bin/mix local.rebar --force && \
    /usr/local/bin/mix hex.info

WORKDIR /app
COPY . .

RUN mix deps.get

ENV MIX_ENV prod
ENTRYPOINT ["/usr/local/bin/mix", "release"]
